package com.worldwidewaves.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006874)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF9EEFFD)
val onPrimaryContainerLight = Color(0xFF001F24)
val secondaryLight = Color(0xFF306A42)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFB3F1BF)
val onSecondaryContainerLight = Color(0xFF00210C)
val tertiaryLight = Color(0xFF006874)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF9EEFFD)
val onTertiaryContainerLight = Color(0xFF001F24)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF5FAFB)
val onBackgroundLight = Color(0xFF171D1E)
val surfaceLight = Color(0xFFF9F9FF)
val onSurfaceLight = Color(0xFF191C20)
val surfaceVariantLight = Color(0xFFDDE5DA)
val onSurfaceVariantLight = Color(0xFF414941)
val outlineLight = Color(0xFF717971)
val outlineVariantLight = Color(0xFFC1C9BF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E3035)
val inverseOnSurfaceLight = Color(0xFFF0F0F7)
val inversePrimaryLight = Color(0xFF82D3E0)
val surfaceDimLight = Color(0xFFD9D9E0)
val surfaceBrightLight = Color(0xFFF9F9FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F3FA)
val surfaceContainerLight = Color(0xFFEDEDF4)
val surfaceContainerHighLight = Color(0xFFE7E8EE)
val surfaceContainerHighestLight = Color(0xFFE1E2E9)

val quaternaryLight = Color(0xFF904B40)
val onQuaternaryLight = Color(0xFFFFFFFF)
val quaternaryContainerLight = Color(0xFFFFDAD4)
val onQuaternaryContainerLight = Color(0xFF3A0905)
val quinaryLight = Color(0xFF8E4D31)
val onQuinaryLight = Color(0xFFFFFFFF)
val quinaryContainerLight = Color(0xFFFFDBCE)
val onQuinaryContainerLight = Color(0xFF370E00)


