excluded:
  - build
  - Pods
  - .build
  - DerivedData
  - worldwidewaves.xcodeproj

included:
  - worldwidewaves

file_length:
  warning: 1500
  error: 2000

type_body_length:
  warning: 400
  error: 500
