name: iosApp
options:
  bundleIdPrefix: com.worldwidewaves
  createIntermediateGroups: true
  developmentLanguage: en
  deploymentTarget:
    iOS: "15.0"
targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - path: iosApp
        excludes:
          - "*.xcodeproj"
          - "build"
          - "DerivedData"
    onDemandResourceTags:
      - name: bangalore_india
        resources:
          - path: Resources/Maps/bangalore_india
        priority: 1.0
      - name: bangkok_thailand
        resources:
          - path: Resources/Maps/bangkok_thailand
        priority: 1.0
      - name: beijing_china
        resources:
          - path: Resources/Maps/beijing_china
        priority: 1.0
      - name: berlin_germany
        resources:
          - path: Resources/Maps/berlin_germany
        priority: 1.0
      - name: bogota_colombia
        resources:
          - path: Resources/Maps/bogota_colombia
        priority: 1.0
      - name: buenos_aires_argentina
        resources:
          - path: Resources/Maps/buenos_aires_argentina
        priority: 1.0
      - name: cairo_egypt
        resources:
          - path: Resources/Maps/cairo_egypt
        priority: 1.0
      - name: chicago_usa
        resources:
          - path: Resources/Maps/chicago_usa
        priority: 1.0
      - name: delhi_india
        resources:
          - path: Resources/Maps/delhi_india
        priority: 1.0
      - name: dubai_united_arab_emirates
        resources:
          - path: Resources/Maps/dubai_united_arab_emirates
        priority: 1.0
      - name: hong_kong_china
        resources:
          - path: Resources/Maps/hong_kong_china
        priority: 1.0
      - name: istanbul_turkey
        resources:
          - path: Resources/Maps/istanbul_turkey
        priority: 1.0
      - name: jakarta_indonesia
        resources:
          - path: Resources/Maps/jakarta_indonesia
        priority: 1.0
      - name: johannesburg_south_africa
        resources:
          - path: Resources/Maps/johannesburg_south_africa
        priority: 1.0
      - name: karachi_pakistan
        resources:
          - path: Resources/Maps/karachi_pakistan
        priority: 1.0
      - name: kinshasa_democratic_republic_of_the_congo
        resources:
          - path: Resources/Maps/kinshasa_democratic_republic_of_the_congo
        priority: 1.0
      - name: lagos_nigeria
        resources:
          - path: Resources/Maps/lagos_nigeria
        priority: 1.0
      - name: lima_peru
        resources:
          - path: Resources/Maps/lima_peru
        priority: 1.0
      - name: london_england
        resources:
          - path: Resources/Maps/london_england
        priority: 1.0
      - name: los_angeles_usa
        resources:
          - path: Resources/Maps/los_angeles_usa
        priority: 1.0
      - name: madrid_spain
        resources:
          - path: Resources/Maps/madrid_spain
        priority: 1.0
      - name: manila_philippines
        resources:
          - path: Resources/Maps/manila_philippines
        priority: 1.0
      - name: melbourne_australia
        resources:
          - path: Resources/Maps/melbourne_australia
        priority: 1.0
      - name: mexico_city_mexico
        resources:
          - path: Resources/Maps/mexico_city_mexico
        priority: 1.0
      - name: moscow_russia
        resources:
          - path: Resources/Maps/moscow_russia
        priority: 1.0
      - name: mumbai_india
        resources:
          - path: Resources/Maps/mumbai_india
        priority: 1.0
      - name: nairobi_kenya
        resources:
          - path: Resources/Maps/nairobi_kenya
        priority: 1.0
      - name: new_york_usa
        resources:
          - path: Resources/Maps/new_york_usa
        priority: 1.0
      - name: paris_france
        resources:
          - path: Resources/Maps/paris_france
        priority: 1.0
      - name: rome_italy
        resources:
          - path: Resources/Maps/rome_italy
        priority: 1.0
      - name: san_francisco_usa
        resources:
          - path: Resources/Maps/san_francisco_usa
        priority: 1.0
      - name: santiago_chile
        resources:
          - path: Resources/Maps/santiago_chile
        priority: 1.0
      - name: sao_paulo_brazil
        resources:
          - path: Resources/Maps/sao_paulo_brazil
        priority: 1.0
      - name: seoul_south_korea
        resources:
          - path: Resources/Maps/seoul_south_korea
        priority: 1.0
      - name: shanghai_china
        resources:
          - path: Resources/Maps/shanghai_china
        priority: 1.0
      - name: sydney_australia
        resources:
          - path: Resources/Maps/sydney_australia
        priority: 1.0
      - name: tehran_iran
        resources:
          - path: Resources/Maps/tehran_iran
        priority: 1.0
      - name: tokyo_japan
        resources:
          - path: Resources/Maps/tokyo_japan
        priority: 1.0
      - name: toronto_canada
        resources:
          - path: Resources/Maps/toronto_canada
        priority: 1.0
      - name: vancouver_canada
        resources:
          - path: Resources/Maps/vancouver_canada
        priority: 1.0
    settings:
      INFOPLIST_FILE: iosApp/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.worldwidewaves.iosApp
      DEVELOPMENT_TEAM: ""
      OTHER_LDFLAGS: [
        "-lc++",
        "-framework", "Shared"
      ]
      FRAMEWORK_SEARCH_PATHS: [
        "../shared/build/xcode-frameworks/$$(CONFIGURATION)/$$(SDK_NAME)"
      ]
    dependencies:
      - framework: ../shared/build/xcode-frameworks/$$(CONFIGURATION)/$$(SDK_NAME)/Shared.framework
        embed: false
schemes:
  iosApp:
    build:
      targets:
        iosApp: all
    run:
      config: Debug
    archive:
      config: Release