name: iosApp
options:
  bundleIdPrefix: com.worldwidewaves
  createIntermediateGroups: true
  developmentLanguage: en
  deploymentTarget:
    iOS: "15.0"
targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - path: iosApp
        excludes:
          - "*.xcodeproj"
          - "build"
          - "DerivedData"
    settings:
      INFOPLIST_FILE: iosApp/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.worldwidewaves.iosApp
      DEVELOPMENT_TEAM: ""
      OTHER_LDFLAGS: [
        "-lc++",
        "-framework", "Shared"
      ]
      FRAMEWORK_SEARCH_PATHS: [
        "../shared/build/bin/iosSimulatorArm64/debugFramework",
        "../shared/build/bin/iosArm64/debugFramework"
      ]
    dependencies:
      - framework: ../shared/build/bin/iosSimulatorArm64/debugFramework/Shared.framework
    preBuildScripts:
      - name: "Build Kotlin Framework"
        script: |
          echo "Building Kotlin framework for iOS..."
          cd ..
          ./gradlew :shared:linkDebugFrameworkIosSimulatorArm64
          ./gradlew :shared:linkDebugFrameworkIosArm64
        embed: false
schemes:
  iosApp:
    build:
      targets:
        iosApp: all
    run:
      config: Debug
    archive:
      config: Release