name: iosApp
options:
  bundleIdPrefix: com.worldwidewaves
  createIntermediateGroups: true
  developmentLanguage: en
  deploymentTarget:
    iOS: "15.0"
targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - path: iosApp
        excludes:
          - "*.xcodeproj"
          - "build"
          - "DerivedData"
    onDemandResourceTags:
      - name: paris_france
        resources:
          - path: Resources/Maps/paris_france
        priority: 1.0
      - name: new_york_usa
        resources:
          - path: Resources/Maps/new_york_usa
        priority: 1.0
      - name: london_england
        resources:
          - path: Resources/Maps/london_england
        priority: 1.0
      - name: berlin_germany
        resources:
          - path: Resources/Maps/berlin_germany
        priority: 1.0
      - name: tokyo_japan
        resources:
          - path: Resources/Maps/tokyo_japan
        priority: 1.0
    settings:
      INFOPLIST_FILE: iosApp/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.worldwidewaves.iosApp
      DEVELOPMENT_TEAM: ""
      OTHER_LDFLAGS: [
        "-lc++",
        "-framework", "Shared"
      ]
      FRAMEWORK_SEARCH_PATHS: [
        "../shared/build/xcode-frameworks/$$(CONFIGURATION)/$$(SDK_NAME)"
      ]
    dependencies:
      - framework: ../shared/build/xcode-frameworks/$$(CONFIGURATION)/$$(SDK_NAME)/Shared.framework
        embed: false
schemes:
  iosApp:
    build:
      targets:
        iosApp: all
    run:
      config: Debug
    archive:
      config: Release