package com.worldwidewaves.shared.utils

/*
 * Copyright 2025 DrWave
 *
 * WorldWideWaves is an ephemeral mobile app designed to orchestrate human waves through cities and
 * countries. The project aims to transcend physical and cultural
 * boundaries, fostering unity, community, and shared human experience by leveraging real-time
 * coordination and location-based services.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import kotlinx.coroutines.async
import kotlinx.coroutines.launch
import kotlinx.coroutines.test.runTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * Tests for [CorrelationContext] distributed tracing functionality.
 *
 * Verifies:
 * - Automatic correlation ID generation
 * - Custom correlation ID assignment
 * - Context propagation to child coroutines
 * - Context isolation between independent operations
 * - Thread safety and coroutine safety
 */
class CorrelationContextTest {
    @Test
    fun testNoCorrelationIdByDefault() =
        runTest {
            val correlationId = CorrelationContext.getCurrentId()
            assertNull(correlationId, "Should have no correlation ID outside of withCorrelation block")
        }

    @Test
    fun testCustomCorrelationId() =
        runTest {
            CorrelationContext.withCorrelation("TEST-123") {
                val correlationId = CorrelationContext.getCurrentId()
                assertEquals("TEST-123", correlationId, "Should use custom correlation ID")
            }
        }

    @Test
    fun testAutoGeneratedCorrelationId() =
        runTest {
            CorrelationContext.withCorrelation {
                val correlationId = CorrelationContext.getCurrentId()
                assertNotNull(correlationId, "Should generate correlation ID automatically")
                assertTrue(
                    correlationId.startsWith("CID-"),
                    "Auto-generated ID should start with CID- prefix",
                )
            }
        }

    @Test
    fun testCorrelationIdPropagationToChildCoroutines() =
        runTest {
            CorrelationContext.withCorrelation("PARENT-456") {
                val parentId = CorrelationContext.getCurrentId()
                assertEquals("PARENT-456", parentId)

                // Launch child coroutine
                launch {
                    val childId = CorrelationContext.getCurrentId()
                    assertEquals(
                        "PARENT-456",
                        childId,
                        "Child coroutine should inherit parent's correlation ID",
                    )
                }
            }
        }

    @Test
    fun testCorrelationIdInAsyncCoroutines() =
        runTest {
            val result =
                CorrelationContext.withCorrelation("ASYNC-789") {
                    val deferred =
                        async {
                            CorrelationContext.getCurrentId()
                        }
                    deferred.await()
                }

            assertEquals("ASYNC-789", result, "Async coroutine should inherit correlation ID")
        }

    @Test
    fun testNestedCorrelationContexts() =
        runTest {
            CorrelationContext.withCorrelation("OUTER-001") {
                val outerId = CorrelationContext.getCurrentId()
                assertEquals("OUTER-001", outerId)

                // Nested correlation context should override parent
                CorrelationContext.withCorrelation("INNER-002") {
                    val innerId = CorrelationContext.getCurrentId()
                    assertEquals("INNER-002", innerId, "Inner context should override outer")
                }

                // After exiting nested context, should revert to outer
                val afterNested = CorrelationContext.getCurrentId()
                assertEquals("OUTER-001", afterNested, "Should revert to outer context after nested block")
            }
        }

    @Test
    fun testCorrelationContextIsolation() =
        runTest {
            // First operation with its own correlation ID
            CorrelationContext.withCorrelation("OP1-123") {
                assertEquals("OP1-123", CorrelationContext.getCurrentId())
            }

            // Second operation should not inherit first operation's ID
            CorrelationContext.withCorrelation("OP2-456") {
                assertEquals("OP2-456", CorrelationContext.getCurrentId())
            }
        }

    @Test
    fun testCorrelationIdClearedAfterBlock() =
        runTest {
            CorrelationContext.withCorrelation("TEMP-999") {
                assertEquals("TEMP-999", CorrelationContext.getCurrentId())
            }

            // After exiting block, correlation ID should be cleared
            val afterBlock = CorrelationContext.getCurrentId()
            assertNull(afterBlock, "Correlation ID should be cleared after exiting withCorrelation block")
        }

    @Test
    fun testMultipleSequentialOperations() =
        runTest {
            val ids = mutableListOf<String?>()

            CorrelationContext.withCorrelation("SEQ-001") {
                ids.add(CorrelationContext.getCurrentId())
            }

            CorrelationContext.withCorrelation("SEQ-002") {
                ids.add(CorrelationContext.getCurrentId())
            }

            CorrelationContext.withCorrelation("SEQ-003") {
                ids.add(CorrelationContext.getCurrentId())
            }

            assertEquals<List<String?>>(listOf("SEQ-001", "SEQ-002", "SEQ-003"), ids)
        }

    @Test
    fun testCorrelationIdFormat() =
        runTest {
            CorrelationContext.withCorrelation {
                val correlationId = CorrelationContext.getCurrentId()
                assertNotNull(correlationId)

                // Should match pattern: CID-XXXXX where X is a digit
                val regex = Regex("^CID-\\d{5}$")
                assertTrue(
                    regex.matches(correlationId),
                    "Auto-generated correlation ID should match format CID-XXXXX, got: $correlationId",
                )
            }
        }

    @Test
    fun testReturnValuePreserved() =
        runTest {
            val result =
                CorrelationContext.withCorrelation("RETURN-TEST") {
                    42
                }

            assertEquals(42, result, "withCorrelation should preserve return value")
        }

    @Test
    fun testComplexDataReturnValue() =
        runTest {
            data class Result(
                val id: String,
                val value: Int,
            )

            val result =
                CorrelationContext.withCorrelation("COMPLEX-TEST") {
                    Result(CorrelationContext.getCurrentId() ?: "unknown", 100)
                }

            assertEquals("COMPLEX-TEST", result.id)
            assertEquals(100, result.value)
        }
}
